// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ipochi/api-mock-example/model (interfaces: Functions)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/ipochi/api-mock-example/model"
	reflect "reflect"
)

// MockFunctions is a mock of Functions interface
type MockFunctions struct {
	ctrl     *gomock.Controller
	recorder *MockFunctionsMockRecorder
}

// MockFunctionsMockRecorder is the mock recorder for MockFunctions
type MockFunctionsMockRecorder struct {
	mock *MockFunctions
}

// NewMockFunctions creates a new mock instance
func NewMockFunctions(ctrl *gomock.Controller) *MockFunctions {
	mock := &MockFunctions{ctrl: ctrl}
	mock.recorder = &MockFunctionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFunctions) EXPECT() *MockFunctionsMockRecorder {
	return m.recorder
}

// GetCompanies mocks base method
func (m *MockFunctions) GetCompanies() ([]model.Company, error) {
	ret := m.ctrl.Call(m, "GetCompanies")
	ret0, _ := ret[0].([]model.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanies indicates an expected call of GetCompanies
func (mr *MockFunctionsMockRecorder) GetCompanies() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanies", reflect.TypeOf((*MockFunctions)(nil).GetCompanies))
}
